"""create message model

Revision ID: 199308fadbae
Revises: b2ea9fbfd82d
Create Date: 2023-06-23 13:06:02.607449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199308fadbae'
down_revision = 'b2ea9fbfd82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
